:sparkles: Adds ability to also format the code
reviewdog/action-black pull request #19
Opened 2020-12-27 15:10 UTC by rickstaa

In this pull request, I added the ability also to format the code. This allows us to automatically create a pull request using the [peter-evans/create-pull-request](https://github.com/peter-evans/create-pull-request) with the required changes. I will add the test report to this pull request.  Let me know what you think and if you have any suggestions.

2020-12-27 23:06 UTC, tsuyoshicho requested changes
Nice work! and basically good.

See suggest and below point.

- Versioning: up minor with add new param(or major?)
- Fix misspell: "occured" is a misspelling of "occurred"
- README write clearly with 2way reviewdog repot and/or black format

2020-12-27 23:06 UTC, tsuyoshicho commented on README.md
> +      uses: reviewdog/action-black@v1.1.2
Use version @v1

2020-12-27 23:06 UTC, tsuyoshicho commented on README.md
> +      uses: reviewdog/action-black@v1.1.2
Same it

2020-12-27 23:06 UTC, tsuyoshicho commented on action.yml
> +  fail_on_error:
What's moved?

If option was related, add more info in description for `format`.

2020-12-28 00:18 UTC, tsuyoshicho commented on action.yml
> +  fail_on_error:
https://github.com/reviewdog/action-black/blob/da08ab17ca7406548245f2d3940f924ad9ff5056/entrypoint.sh#L75-L78

(note)

2020-12-28 08:08 UTC, rickstaa commented on README.md
> +      uses: reviewdog/action-black@v1.1.2
Good catch!

2020-12-28 09:24 UTC, tsuyoshicho approved these changes
Good!
If you need more improvement, treat code indent/spacing.

2020-12-28 11:29 UTC, rickstaa commented
✅ [Tests results (success)](https://github.com/rickstaa/action-test-repo/runs/1617074126?check_suite_focus=true)

2020-12-28 11:50 UTC, merged